In [1]:
from datasets import load_dataset

faq_hu = load_dataset("clips/mqa", scope="faq", language="hu")

Using custom data configuration hu-faq-question-language=hu,scope=faq
Reusing dataset mqa (/Users/eend/.cache/huggingface/datasets/clips___mqa/hu-faq-question-language=hu,scope=faq/0.0.0/7eda4cdcbd6f009259fc516f204d776915a5f54ea2ad414c3dcddfaacd4dfe0b)
100%|██████████| 1/1 [00:00<00:00, 19.53it/s]


In [8]:
faq_hu['train'][810000]

{'id': 'a44ad85683f3d8afd1ffa42ce55fefcd',
 'text': '',
 'name': 'szingapúr területén mely kisállatbarát hotelek ideálisak a családok számára?',
 'domain': 'tripadvisor.co.hu',
 'bucket': '2020.29',
 'answers': [{'text': 'a(z) szingapúr területén nyaraló családok tapasztalatai szerint ezek igazán jó kisállatbarát hotelek:  \n**[intercontinental singapore](https://www.tripadvisor.co.hu/hotel_review-g294265-d299199-reviews-intercontinental_singapore-singapore.html?faqtqr=5&faqts=hotels&faqtt=214&faqtup=geo%3a294265%3bzfa%3a9&m=63287)** utazói osztályozás: 4.5/5  \n**[fraser suites singapore](https://www.tripadvisor.co.hu/hotel_review-g294265-d306172-reviews-fraser_suites_singapore-singapore.html?faqtqr=5&faqts=hotels&faqtt=214&faqtup=geo%3a294265%3bzfa%3a9&m=63287)** utazói osztályozás: 4.5/5  \n**[holiday inn express singapore katong](https://www.tripadvisor.co.hu/hotel_review-g294265-d8777586-reviews-holiday_inn_express_singapore_katong-singapore.html?faqtqr=5&faqts=hotels&faqtt=214&fa

In [16]:
import torch

a = torch.tensor([[1,2,2,3,4],[2,3,4,5,7]])
b = a * 2

tensor_list = []
tensor_list.append(a)
tensor_list.append(b)
torch.cat((a,b),dim=0)

tensor([[ 1,  2,  2,  3,  4],
        [ 2,  3,  4,  5,  7],
        [ 2,  4,  4,  6,  8],
        [ 4,  6,  8, 10, 14]])

In [17]:
a.size()[1]

5

In [18]:
a[:2]

tensor([[1, 2, 2, 3, 4],
        [2, 3, 4, 5, 7]])

In [24]:
a.tolist()

[[1, 2, 2, 3, 4], [2, 3, 4, 5, 7]]

In [25]:
c = torch.empty([1,5])

In [26]:
c

tensor([[1.4569e-19, 1.0658e-32, 1.1258e+24, 1.5789e-19, 1.1819e+22]])

In [28]:
c.squeeze().tolist()

[1.4568973155122501e-19,
 1.0658291767562146e-32,
 1.1257918204515671e+24,
 1.5789373458898217e-19,
 1.1818655764620037e+22]

In [32]:
a = [1,2,3]
b= [2,4,5]
print(a.extend(b))

None


[1, 2, 3, 2, 4, 5]

In [41]:
with open('../approach.txt','r') as f:
    line = 'init'
    while line != '':
        line=f.readline();
        print(line)



Types of Question Answering

    - extractive question answering (encoder only models BERT)

        - posing questions about a document and identifying the answers as spans of text in the document itself

    - generative question answering (encoder-decoder T5/BART)

        - open ended questions, which need to synthesize information

    - retrieval based/community question answering 







First approach - translate dataset, fine-tune model

!Not really feasible, because it needs lots of human evaluation for correctly determine answer start token



    1. Translate English QA dataset into Hungarian

        - SQuAD - reading comprehension based on Wikipedia articles

        - ~ 100.000 question/answers

    2. Fine-tune a model and evaluate on this dataset





Second approach - fine-tune multilingual model

!MQA format different than SQuAD, cannot use ModelForQuestionAnswering



    1. Use a Hungarian dataset

        - MQA - multilingual parsed from Common Crawl

          

In [42]:
d = torch.empty([20])
d

tensor([1.4013e-45, 0.0000e+00, 2.8026e-45, 0.0000e+00, 2.8026e-45, 0.0000e+00,
        4.2039e-45, 0.0000e+00, 5.6052e-45, 0.0000e+00, 2.8026e-45, 0.0000e+00,
        4.2039e-45, 0.0000e+00, 5.6052e-45, 0.0000e+00, 7.0065e-45, 0.0000e+00,
        9.8091e-45, 0.0000e+00])